# Pipeline Refactor Experimentation

In [1]:
from src.pipeline.model_pipeline import ScreentimeModelPipeline

C:\Users\jjmur\PycharmProjects\lemurs-ml\src\database_service.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, self.connection)
C:\Users\jjmur\PycharmProjects\lemurs-ml\src\categorization\PHQ9_categorization_binary.py:49: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql, conn)
C:\Users\jjmur\PycharmProjects\lemurs-ml\src\categorization\suicide_risk_labels.py:88: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql, conn)
C:\Users\jjmur\PycharmProjects\lemurs-ml\src\categorization\daily_questions_categorization.py:225: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(sql, conn)

## Example usage with the screentime window pipeline

In [2]:
pipeline = ScreentimeModelPipeline(
    target_type='sleep',
    time_windows=[3,6,9,12],
    save_confusion_matrices=True
)
results = pipeline.fit_predict();

================================================================================
EXTRACTING AND PROCESSING DATA
================================================================================

================================================================================
MODELING TIME WINDOW: 3 HOURS
================================================================================

Logistic Regression:
  Accuracy: 0.7500
  F1 Score: 0.8421
  AUC: 0.4688

Random Forest:
  Accuracy: 0.7500
  F1 Score: 0.8421
  AUC: 0.4219

================================================================================
MODELING TIME WINDOW: 6 HOURS
================================================================================

Logistic Regression:
  Accuracy: 0.7778
  F1 Score: 0.8710
  AUC: 0.3661

Random Forest:
  Accuracy: 0.7500
  F1 Score: 0.8475
  AUC: 0.4777

================================================================================
MODELING TIME WINDOW: 9 HOURS
================================================================================

Logistic Regression:
  Accuracy: 0.7778
  F1 Score: 0.8710
  AUC: 0.3661

Random Forest:
  Accuracy: 0.7500
  F1 Score: 0.8475
  AUC: 0.4777

================================================================================
MODELING TIME WINDOW: 12 HOURS
================================================================================

Logistic Regression:
  Accuracy: 0.7447
  F1 Score: 0.8500
  AUC: 0.2476

Random Forest:
  Accuracy: 0.6809
  F1 Score: 0.7826
  AUC: 0.3762
Saved all windows confusion matrices to: C:\Users\jjmur\PycharmProjects\lemurs-ml\data\confusion_matrices_sleep.png
Saved best models confusion matrices to: C:\Users\jjmur\PycharmProjects\lemurs-ml\data\confusion_matrices_sleep_best.png

================================================================================
SUMMARY - ALL TIME WINDOWS
================================================================================

Logistic Regression:
  Window     F1 Score     Accuracy          AUC
------------------------------------------------
     3h       0.8421       0.7500       0.4688
     6h       0.8710       0.7778       0.3661
     9h       0.8710       0.7778       0.3661
    12h       0.8500       0.7447       0.2476

  Best Window: 6h (F1=0.8710)

  Confusion Matrix (Best Window):
                  Predicted
                   not_at_risk      at_risk
  Actual
      not_at_risk            1            7
          at_risk            1           27


Random Forest:
  Window     F1 Score     Accuracy          AUC
------------------------------------------------
     3h       0.8421       0.7500       0.4219
     6h       0.8475       0.7500       0.4777
     9h       0.8475       0.7500       0.4777
    12h       0.7826       0.6809       0.3762

  Best Window: 6h (F1=0.8475)

  Confusion Matrix (Best Window):
                  Predicted
                   not_at_risk      at_risk
  Actual
      not_at_risk            2            6
          at_risk            3           25

## View Processed Screentime Data

After `fit_predict()` runs, the processed data is stored in `pipeline.processed_data_`.
This is a dictionary where keys are time windows (hours) and values are DataFrames with screentime features.

In [3]:
# View available time windows
print("Available time windows:", list(pipeline.processed_data_.keys()))
print()

# Display data for each time window
for window, df in pipeline.processed_data_.items():
    print(f"\n{'='*80}")
    print(f"SCREENTIME DATA - {window} HOUR WINDOW")
    print(f"{'='*80}")
    print(f"Shape: {df.shape[0]} rows × {df.shape[1]} columns")
    print(f"\nFirst 20 rows:")
    display(df.head(20))

Available time windows: [3, 6, 9, 12]


================================================================================
SCREENTIME DATA - 3 HOUR WINDOW
================================================================================
Shape: 37 rows × 7 columns

First 20 rows:

,app_user_id,survey_response_id,survey_timestamp,hour_0,hour_1,hour_2,sleep_label
0,5,7,2025-11-18 08:56:49.320,0.000,0.000,5757.356,not_at_risk
1,5,45,2025-11-20 09:19:54.915,0.000,0.000,6786.366,at_risk
2,5,58,2025-11-21 08:51:15.591,0.000,0.000,6484.552,at_risk
3,5,102,2025-11-23 09:53:29.593,0.000,0.000,0.000,at_risk
4,5,124,2025-11-24 09:53:57.127,0.000,0.000,0.000,at_risk
5,5,138,2025-11-25 08:18:50.539,0.000,4333.677,0.000,at_risk
6,6,13,2025-11-18 10:50:54.742,0.000,0.000,0.000,at_risk
15,8,12,2025-11-18 10:34:43.390,0.000,0.000,0.000,at_risk
16,8,67,2025-11-21 10:34:24.726,0.000,0.000,0.000,at_risk
17,8,87,2025-11-22 10:55:51.488,0.000,0.000,0.000,at_risk
18,8,156,2025-11-26 08:35:18.517,0.000,25097.560,0.000,at_risk
19,8,157,2025-11-26 08:35:20.332,0.000,25097.560,0.000,at_risk
20,8,459,2025-12-10 12:34:18.158,0.000,0.000,3600.420,not_at_risk
21,9,125,2025-11-24 10:39:07.420,0.000,24978.874,0.000,at_risk
22,9,145,2025-11-25 10:01:04.183,24924.598,0.000,0.000,at_risk
23,9,166,2025-11-26 11:28:25.120,0.000,1845.776,0.000,at_risk
24,16,296,2025-12-03 08:44:48.488,0.000,0.000,9373.948,at_risk
25,16,298,2025-12-03 08:44:53.883,0.000,0.000,9373.948,at_risk
26,16,297,2025-12-03 08:45:00.148,0.000,0.000,9373.948,at_risk
27,16,431,2025-12-09 09:55:09.890,0.000,0.000,0.000,at_risk

================================================================================
SCREENTIME DATA - 6 HOUR WINDOW
================================================================================
Shape: 119 rows × 10 columns

First 20 rows:

,app_user_id,survey_response_id,survey_timestamp,hour_0,hour_1,hour_2,hour_3,hour_4,hour_5,sleep_label
0,5,1,2025-11-15 10:17:54.641,0.0,0.000,0.000,0.000,10519.377,0.000,at_risk
1,5,3,2025-11-16 10:34:25.655,0.0,0.000,0.000,0.000,0.000,11160.763,at_risk
2,5,5,2025-11-17 10:59:22.663,0.0,0.000,0.000,0.000,0.000,4295.951,not_at_risk
3,5,7,2025-11-18 08:56:49.320,0.0,0.000,5757.356,0.000,0.000,0.000,not_at_risk
4,5,27,2025-11-19 11:04:46.601,0.0,0.000,0.000,0.000,11716.922,0.000,at_risk
5,5,45,2025-11-20 09:19:54.915,0.0,0.000,6786.366,0.000,0.000,0.000,at_risk
6,5,58,2025-11-21 08:51:15.591,0.0,0.000,6484.552,0.000,0.000,0.000,at_risk
7,5,84,2025-11-22 10:27:47.946,0.0,0.000,0.000,9468.524,0.000,0.000,at_risk
8,5,102,2025-11-23 09:53:29.593,0.0,0.000,0.000,10454.827,0.000,0.000,at_risk
9,5,124,2025-11-24 09:53:57.127,0.0,0.000,0.000,3179.372,0.000,0.000,at_risk
10,5,138,2025-11-25 08:18:50.539,0.0,4333.677,0.000,0.000,0.000,0.000,at_risk
11,5,162,2025-11-26 10:09:52.676,0.0,0.000,0.000,13150.880,0.000,0.000,at_risk
12,5,184,2025-11-27 10:59:30.391,0.0,0.000,0.000,0.000,8101.762,0.000,at_risk
13,5,201,2025-11-28 10:59:25.084,0.0,0.000,0.000,0.000,19860.930,0.000,at_risk
14,5,222,2025-11-29 10:58:41.386,0.0,0.000,0.000,0.000,13159.431,0.000,at_risk
15,5,241,2025-11-30 11:18:22.172,0.0,0.000,0.000,0.000,6491.730,0.000,at_risk
16,5,277,2025-12-02 11:19:25.151,0.0,0.000,0.000,0.000,7086.040,0.000,at_risk
17,5,304,2025-12-03 12:23:14.626,0.0,0.000,0.000,0.000,0.000,8201.060,at_risk
18,5,330,2025-12-04 12:34:13.033,0.0,0.000,0.000,0.000,0.000,0.000,at_risk
19,5,350,2025-12-05 12:17:38.224,0.0,0.000,0.000,0.000,0.000,6438.732,at_risk

================================================================================
SCREENTIME DATA - 9 HOUR WINDOW
================================================================================
Shape: 119 rows × 13 columns

First 20 rows:

,app_user_id,survey_response_id,survey_timestamp,hour_0,hour_1,hour_2,hour_3,hour_4,hour_5,hour_6,hour_7,hour_8,sleep_label
0,5,1,2025-11-15 10:17:54.641,0.0,0.000,0.000,0.000,10519.377,0.000,0.000,0.0,0.0,at_risk
1,5,3,2025-11-16 10:34:25.655,0.0,0.000,0.000,0.000,0.000,11160.763,0.000,0.0,0.0,at_risk
2,5,5,2025-11-17 10:59:22.663,0.0,0.000,0.000,0.000,0.000,4295.951,0.000,0.0,0.0,not_at_risk
3,5,7,2025-11-18 08:56:49.320,0.0,0.000,5757.356,0.000,0.000,0.000,0.000,0.0,0.0,not_at_risk
4,5,27,2025-11-19 11:04:46.601,0.0,0.000,0.000,0.000,11716.922,0.000,0.000,0.0,0.0,at_risk
5,5,45,2025-11-20 09:19:54.915,0.0,0.000,6786.366,0.000,0.000,0.000,0.000,0.0,0.0,at_risk
6,5,58,2025-11-21 08:51:15.591,0.0,0.000,6484.552,0.000,0.000,0.000,0.000,0.0,0.0,at_risk
7,5,84,2025-11-22 10:27:47.946,0.0,0.000,0.000,9468.524,0.000,0.000,0.000,0.0,0.0,at_risk
8,5,102,2025-11-23 09:53:29.593,0.0,0.000,0.000,10454.827,0.000,0.000,0.000,0.0,0.0,at_risk
9,5,124,2025-11-24 09:53:57.127,0.0,0.000,0.000,3179.372,0.000,0.000,0.000,0.0,0.0,at_risk
10,5,138,2025-11-25 08:18:50.539,0.0,4333.677,0.000,0.000,0.000,0.000,0.000,0.0,0.0,at_risk
11,5,162,2025-11-26 10:09:52.676,0.0,0.000,0.000,13150.880,0.000,0.000,0.000,0.0,0.0,at_risk
12,5,184,2025-11-27 10:59:30.391,0.0,0.000,0.000,0.000,8101.762,0.000,0.000,0.0,0.0,at_risk
13,5,201,2025-11-28 10:59:25.084,0.0,0.000,0.000,0.000,19860.930,0.000,0.000,0.0,0.0,at_risk
14,5,222,2025-11-29 10:58:41.386,0.0,0.000,0.000,0.000,13159.431,0.000,0.000,0.0,0.0,at_risk
15,5,241,2025-11-30 11:18:22.172,0.0,0.000,0.000,0.000,6491.730,0.000,0.000,0.0,0.0,at_risk
16,5,277,2025-12-02 11:19:25.151,0.0,0.000,0.000,0.000,7086.040,0.000,0.000,0.0,0.0,at_risk
17,5,304,2025-12-03 12:23:14.626,0.0,0.000,0.000,0.000,0.000,8201.060,0.000,0.0,0.0,at_risk
18,5,330,2025-12-04 12:34:13.033,0.0,0.000,0.000,0.000,0.000,0.000,12470.634,0.0,0.0,at_risk
19,5,350,2025-12-05 12:17:38.224,0.0,0.000,0.000,0.000,0.000,6438.732,0.000,0.0,0.0,at_risk

================================================================================
SCREENTIME DATA - 12 HOUR WINDOW
================================================================================
Shape: 156 rows × 16 columns

First 20 rows:

,app_user_id,survey_response_id,survey_timestamp,hour_0,hour_1,hour_2,hour_3,hour_4,hour_5,hour_6,hour_7,hour_8,hour_9,hour_10,hour_11,sleep_label
0,5,1,2025-11-15 10:17:54.641,0.0,0.000,0.000,0.000,10519.377,0.000,0.000,0.0,0.0,0.0,0.0,0.0,at_risk
2,5,3,2025-11-16 10:34:25.655,0.0,0.000,0.000,0.000,0.000,11160.763,0.000,0.0,0.0,0.0,0.0,0.0,at_risk
4,5,5,2025-11-17 10:59:22.663,0.0,0.000,0.000,0.000,0.000,4295.951,0.000,0.0,0.0,0.0,0.0,0.0,not_at_risk
5,5,7,2025-11-18 08:56:49.320,0.0,0.000,5757.356,0.000,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,not_at_risk
7,5,27,2025-11-19 11:04:46.601,0.0,0.000,0.000,0.000,11716.922,0.000,0.000,0.0,0.0,0.0,0.0,0.0,at_risk
8,5,45,2025-11-20 09:19:54.915,0.0,0.000,6786.366,0.000,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,at_risk
9,5,58,2025-11-21 08:51:15.591,0.0,0.000,6484.552,0.000,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,at_risk
11,5,84,2025-11-22 10:27:47.946,0.0,0.000,0.000,9468.524,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,at_risk
12,5,102,2025-11-23 09:53:29.593,0.0,0.000,0.000,10454.827,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,at_risk
14,5,124,2025-11-24 09:53:57.127,0.0,0.000,0.000,3179.372,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,at_risk
16,5,138,2025-11-25 08:18:50.539,0.0,4333.677,0.000,0.000,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,at_risk
18,5,162,2025-11-26 10:09:52.676,0.0,0.000,0.000,13150.880,0.000,0.000,0.000,0.0,0.0,0.0,0.0,0.0,at_risk
20,5,184,2025-11-27 10:59:30.391,0.0,0.000,0.000,0.000,8101.762,0.000,0.000,0.0,0.0,0.0,0.0,0.0,at_risk
22,5,201,2025-11-28 10:59:25.084,0.0,0.000,0.000,0.000,19860.930,0.000,0.000,0.0,0.0,0.0,0.0,0.0,at_risk
23,5,222,2025-11-29 10:58:41.386,0.0,0.000,0.000,0.000,13159.431,0.000,0.000,0.0,0.0,0.0,0.0,0.0,at_risk
24,5,241,2025-11-30 11:18:22.172,0.0,0.000,0.000,0.000,6491.730,0.000,0.000,0.0,0.0,0.0,0.0,0.0,at_risk
25,5,277,2025-12-02 11:19:25.151,0.0,0.000,0.000,0.000,7086.040,0.000,0.000,0.0,0.0,0.0,0.0,0.0,at_risk
27,5,304,2025-12-03 12:23:14.626,0.0,0.000,0.000,0.000,0.000,8201.060,0.000,0.0,0.0,0.0,0.0,0.0,at_risk
28,5,330,2025-12-04 12:34:13.033,0.0,0.000,0.000,0.000,0.000,0.000,12470.634,0.0,0.0,0.0,0.0,0.0,at_risk
29,5,350,2025-12-05 12:17:38.224,0.0,0.000,0.000,0.000,0.000,6438.732,0.000,0.0,0.0,0.0,0.0,0.0,at_risk

## View Specific Time Window

You can also access a specific time window directly:

In [4]:
# Example: View 6-hour window data
window_6h = pipeline.processed_data_[6]

print(f"6-hour window data shape: {window_6h.shape}")
print(f"\nLabel distribution:")
print(window_6h['sleep_label'].value_counts())
print(f"\nSample of hourly screentime features:")
display(window_6h[['app_user_id', 'sleep_label', 'hour_0', 'hour_1', 'hour_2', 'hour_3', 'hour_4', 'hour_5']].head(10))

6-hour window data shape: (119, 10)

Label distribution:
sleep_label
at_risk        92
not_at_risk    27
Name: count, dtype: int64

Sample of hourly screentime features:

,app_user_id,sleep_label,hour_0,hour_1,hour_2,hour_3,hour_4,hour_5
0,5,at_risk,0.0,0.0,0.000,0.000,10519.377,0.000
1,5,at_risk,0.0,0.0,0.000,0.000,0.000,11160.763
2,5,not_at_risk,0.0,0.0,0.000,0.000,0.000,4295.951
3,5,not_at_risk,0.0,0.0,5757.356,0.000,0.000,0.000
4,5,at_risk,0.0,0.0,0.000,0.000,11716.922,0.000
5,5,at_risk,0.0,0.0,6786.366,0.000,0.000,0.000
6,5,at_risk,0.0,0.0,6484.552,0.000,0.000,0.000
7,5,at_risk,0.0,0.0,0.000,9468.524,0.000,0.000
8,5,at_risk,0.0,0.0,0.000,10454.827,0.000,0.000
9,5,at_risk,0.0,0.0,0.000,3179.372,0.000,0.000

## Screentime Subwindow Experimentation

This implementation COMBINES traditional hourly screentime features WITH
app category-based sub-window features for richer model input.

In [5]:
subwindow_pipeline = ScreentimeModelPipeline(
    target_type='sleep',
    use_subwindows=True,        # Enable sub-window mode (ADDS to hourly features)
    lookback_hours=12,           # 12-hour lookback
    subwindow_hours=3,           # 3-hour sub-windows
    save_confusion_matrices=True
)
subwindow_results = subwindow_pipeline.fit_predict();

================================================================================
EXTRACTING AND PROCESSING DATA
================================================================================
================================================================================
MERGING SUB-WINDOW SCREENTIME FEATURES WITH SLEEP_LABEL
  Lookback: 12h, Sub-window: 3h
================================================================================
================================================================================
LOADING AND CLEANING SCREENTIME DATA
================================================================================

C:\Users\jjmur\PycharmProjects\lemurs-ml\src\database_service.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, self.connection)

Loaded 78,743 records from database with categories

Records before deduplication: 78,743

C:\Users\jjmur\PycharmProjects\lemurs-ml\src\database_service.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, self.connection)

Records after deduplication: 32,537
Records removed: 46,206

Processing 676 survey responses with sleep_label...

Generated 676 rows with sub-window features
Columns: ['most_used_category_sw0', 'most_used_category_time_sw0', 'num_apps_sw0', 'most_used_category_sw1', 'most_used_category_time_sw1', 'num_apps_sw1', 'most_used_category_sw2', 'most_used_category_time_sw2', 'num_apps_sw2', 'most_used_category_sw3', 'most_used_category_time_sw3', 'num_apps_sw3', 'app_user_id', 'survey_response_id', 'timestamp', 'sleep_label']

Label distribution:
sleep_label
N/A            335
at_risk        181
not_at_risk    160
Name: count, dtype: int64
Combined features: 12 hourly + 12 sub-window features

================================================================================
MODELING TIME WINDOW: 12 HOURS
================================================================================
Warning: Dropping non-numeric columns: ['most_used_category_sw0', 'most_used_category_sw1', 'most_used_category_sw2', 'most_used_category_sw3']

C:\Users\jjmur\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression:
  Accuracy: 0.7021
  F1 Score: 0.8205
  AUC: 0.3667

Random Forest:
  Accuracy: 0.7660
  F1 Score: 0.8608
  AUC: 0.2762
Saved all windows confusion matrices to: C:\Users\jjmur\PycharmProjects\lemurs-ml\data\confusion_matrices_sleep.png
Saved best models confusion matrices to: C:\Users\jjmur\PycharmProjects\lemurs-ml\data\confusion_matrices_sleep_best.png

================================================================================
SUMMARY - ALL TIME WINDOWS
================================================================================

Logistic Regression:
  Window     F1 Score     Accuracy          AUC
------------------------------------------------
    12h       0.8205       0.7021       0.3667

  Best Window: 12h (F1=0.8205)

  Confusion Matrix (Best Window):
                  Predicted
                   not_at_risk      at_risk
  Actual
      not_at_risk            1           11
          at_risk            3           32


Random Forest:
  Window     F1 Score     Accuracy          AUC
------------------------------------------------
    12h       0.8608       0.7660       0.2762

  Best Window: 12h (F1=0.8608)

  Confusion Matrix (Best Window):
                  Predicted
                   not_at_risk      at_risk
  Actual
      not_at_risk            2           10
          at_risk            1           34

In [6]:
# Get the combined features (dict with lookback_hours as key)
combined_data = subwindow_pipeline.processed_data_[12]

print(f"Combined features shape: {combined_data.shape}")
print(f"\nColumns ({len(combined_data.columns)} total):")

# Count feature types
hourly_cols = [c for c in combined_data.columns if c.startswith('hour_')]
subwindow_cols = [c for c in combined_data.columns if c.startswith(('most_used', 'num_apps'))]

print(f"  - Hourly features: {len(hourly_cols)}")
print(f"  - Sub-window features: {len(subwindow_cols)}")
print(f"  - Total features: {len(hourly_cols) + len(subwindow_cols)}")

print(f"\nAll columns:")
print(list(combined_data.columns))

print(f"\nFirst 10 rows:")
display(combined_data.head(10))

Combined features shape: (156, 28)

Columns (28 total):
  - Hourly features: 12
  - Sub-window features: 12
  - Total features: 24

All columns:
['app_user_id', 'survey_response_id', 'survey_timestamp', 'hour_0', 'hour_1', 'hour_2', 'hour_3', 'hour_4', 'hour_5', 'hour_6', 'hour_7', 'hour_8', 'hour_9', 'hour_10', 'hour_11', 'sleep_label', 'most_used_category_sw0', 'most_used_category_time_sw0', 'num_apps_sw0', 'most_used_category_sw1', 'most_used_category_time_sw1', 'num_apps_sw1', 'most_used_category_sw2', 'most_used_category_time_sw2', 'num_apps_sw2', 'most_used_category_sw3', 'most_used_category_time_sw3', 'num_apps_sw3']

First 10 rows:

,app_user_id,survey_response_id,survey_timestamp,hour_0,hour_1,hour_2,hour_3,hour_4,hour_5,hour_6,...,num_apps_sw0,most_used_category_sw1,most_used_category_time_sw1,num_apps_sw1,most_used_category_sw2,most_used_category_time_sw2,num_apps_sw2,most_used_category_sw3,most_used_category_time_sw3,num_apps_sw3
0,5,1,2025-11-15 10:17:54.641,0.0,0.0,0.000,0.000,10519.377,0.000,0.0,...,12,None,0.000000,0,VIDEO_PLAYERS,113.940283,4,SOCIAL,266.221817,18
2,5,3,2025-11-16 10:34:25.655,0.0,0.0,0.000,0.000,0.000,11160.763,0.0,...,4,None,0.000000,0,None,0.000000,0,SOCIAL,235.342433,14
4,5,5,2025-11-17 10:59:22.663,0.0,0.0,0.000,0.000,0.000,4295.951,0.0,...,9,PERSONALIZATION,28.815983,10,None,0.000000,0,None,0.000000,0
5,5,7,2025-11-18 08:56:49.320,0.0,0.0,5757.356,0.000,0.000,0.000,0.0,...,8,None,0.000000,0,None,0.000000,0,COMMUNICATION,86.351600,10
7,5,27,2025-11-19 11:04:46.601,0.0,0.0,0.000,0.000,11716.922,0.000,0.0,...,10,None,0.000000,0,None,0.000000,0,COMMUNICATION,82.046850,9
8,5,45,2025-11-20 09:19:54.915,0.0,0.0,6786.366,0.000,0.000,0.000,0.0,...,14,None,0.000000,0,None,0.000000,0,COMMUNICATION,154.734333,11
9,5,58,2025-11-21 08:51:15.591,0.0,0.0,6484.552,0.000,0.000,0.000,0.0,...,12,None,0.000000,0,None,0.000000,0,SOCIAL,181.776700,6
11,5,84,2025-11-22 10:27:47.946,0.0,0.0,0.000,9468.524,0.000,0.000,0.0,...,5,None,0.000000,0,None,0.000000,0,SOCIAL,198.692417,11
12,5,102,2025-11-23 09:53:29.593,0.0,0.0,0.000,10454.827,0.000,0.000,0.0,...,3,None,0.000000,0,COMMUNICATION,158.011983,4,SOCIAL,123.107700,8
14,5,124,2025-11-24 09:53:57.127,0.0,0.0,0.000,3179.372,0.000,0.000,0.0,...,8,TOOLS,0.254667,1,None,0.000000,0,COMMUNICATION,167.142383,8

Model appears to be more accurate with the combined features

In [7]:
subwindow_self_harm_pipeline = ScreentimeModelPipeline(
    target_type='self_harm',
    use_subwindows=True,        # Enable sub-window mode (ADDS to hourly features)
    lookback_hours=12,           # 12-hour lookback
    subwindow_hours=3,           # 3-hour sub-windows
    save_confusion_matrices=True
)
subwindow_self_harm_results = subwindow_self_harm_pipeline.fit_predict();

================================================================================
EXTRACTING AND PROCESSING DATA
================================================================================
================================================================================
MERGING SUB-WINDOW SCREENTIME FEATURES WITH SELF_HARM_RISK_LABEL
  Lookback: 12h, Sub-window: 3h
================================================================================
================================================================================
LOADING AND CLEANING SCREENTIME DATA
================================================================================

C:\Users\jjmur\PycharmProjects\lemurs-ml\src\database_service.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, self.connection)

Loaded 78,743 records from database with categories

Records before deduplication: 78,743
Records after deduplication: 32,537
Records removed: 46,206

Processing 676 survey responses with self_harm_risk_label...

C:\Users\jjmur\PycharmProjects\lemurs-ml\src\database_service.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, self.connection)

Generated 676 rows with sub-window features
Columns: ['most_used_category_sw0', 'most_used_category_time_sw0', 'num_apps_sw0', 'most_used_category_sw1', 'most_used_category_time_sw1', 'num_apps_sw1', 'most_used_category_sw2', 'most_used_category_time_sw2', 'num_apps_sw2', 'most_used_category_sw3', 'most_used_category_time_sw3', 'num_apps_sw3', 'app_user_id', 'survey_response_id', 'timestamp', 'self_harm_risk_label']

Label distribution:
self_harm_risk_label
not_at_risk    616
at_risk         60
Name: count, dtype: int64
Combined features: 12 hourly + 12 sub-window features

================================================================================
MODELING TIME WINDOW: 12 HOURS
================================================================================
Warning: Dropping non-numeric columns: ['most_used_category_sw0', 'most_used_category_sw1', 'most_used_category_sw2', 'most_used_category_sw3']

C:\Users\jjmur\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression:
  Accuracy: 0.8485
  F1 Score: 0.2857
  AUC: 0.3126

Random Forest:
  Accuracy: 0.9091
  F1 Score: 0.6400
  AUC: 0.1672
Saved all windows confusion matrices to: C:\Users\jjmur\PycharmProjects\lemurs-ml\data\confusion_matrices_self_harm.png
Saved best models confusion matrices to: C:\Users\jjmur\PycharmProjects\lemurs-ml\data\confusion_matrices_self_harm_best.png

================================================================================
SUMMARY - ALL TIME WINDOWS
================================================================================

Logistic Regression:
  Window     F1 Score     Accuracy          AUC
------------------------------------------------
    12h       0.2857       0.8485       0.3126

  Best Window: 12h (F1=0.2857)

  Confusion Matrix (Best Window):
                  Predicted
                   not_at_risk      at_risk
  Actual
      not_at_risk           81            4
          at_risk           11            3


Random Forest:
  Window     F1 Score     Accuracy          AUC
------------------------------------------------
    12h       0.6400       0.9091       0.1672

  Best Window: 12h (F1=0.6400)

  Confusion Matrix (Best Window):
                  Predicted
                   not_at_risk      at_risk
  Actual
      not_at_risk           82            3
          at_risk            6            8

In [8]:
subwindow_self_harm_data = subwindow_self_harm_pipeline.processed_data_[12]

print(f"Combined features shape: {subwindow_self_harm_data.shape}")
print(f"\nColumns ({len(subwindow_self_harm_data.columns)} total):")

# Count feature types
hourly_cols = [c for c in subwindow_self_harm_data.columns if c.startswith('hour_')]
subwindow_cols = [c for c in subwindow_self_harm_data.columns if c.startswith(('most_used', 'num_apps'))]

print(f"  - Hourly features: {len(hourly_cols)}")
print(f"  - Sub-window features: {len(subwindow_cols)}")
print(f"  - Total features: {len(hourly_cols) + len(subwindow_cols)}")

print(f"\nAll columns:")
print(list(subwindow_self_harm_data.columns))

print(f"\nFirst 10 rows:")
display(subwindow_self_harm_data.head(10))

Combined features shape: (329, 28)

Columns (28 total):
  - Hourly features: 12
  - Sub-window features: 12
  - Total features: 24

All columns:
['app_user_id', 'survey_response_id', 'survey_timestamp', 'hour_0', 'hour_1', 'hour_2', 'hour_3', 'hour_4', 'hour_5', 'hour_6', 'hour_7', 'hour_8', 'hour_9', 'hour_10', 'hour_11', 'self_harm_risk_label', 'most_used_category_sw0', 'most_used_category_time_sw0', 'num_apps_sw0', 'most_used_category_sw1', 'most_used_category_time_sw1', 'num_apps_sw1', 'most_used_category_sw2', 'most_used_category_time_sw2', 'num_apps_sw2', 'most_used_category_sw3', 'most_used_category_time_sw3', 'num_apps_sw3']

First 10 rows:

,app_user_id,survey_response_id,survey_timestamp,hour_0,hour_1,hour_2,hour_3,hour_4,hour_5,hour_6,...,num_apps_sw0,most_used_category_sw1,most_used_category_time_sw1,num_apps_sw1,most_used_category_sw2,most_used_category_time_sw2,num_apps_sw2,most_used_category_sw3,most_used_category_time_sw3,num_apps_sw3
0,5,1,2025-11-15 10:17:54.641,0.0,0.0,0.000,0.0,10519.377,0.000,0.0,...,12,None,0.000000,0,VIDEO_PLAYERS,113.940283,4,SOCIAL,266.221817,18
1,5,2,2025-11-15 17:52:03.295,0.0,0.0,0.000,0.0,0.000,0.000,0.0,...,18,SOCIAL,69.379500,13,VIDEO_PLAYERS,151.776867,14,COMMUNICATION,0.053600,2
2,5,3,2025-11-16 10:34:25.655,0.0,0.0,0.000,0.0,0.000,11160.763,0.0,...,4,None,0.000000,0,None,0.000000,0,SOCIAL,235.342433,14
3,5,4,2025-11-16 17:03:13.659,0.0,0.0,0.000,0.0,0.000,0.000,0.0,...,11,SOCIAL,71.748417,11,VIDEO_PLAYERS,14.553150,12,None,0.000000,0
4,5,5,2025-11-17 10:59:22.663,0.0,0.0,0.000,0.0,0.000,4295.951,0.0,...,9,PERSONALIZATION,28.815983,10,None,0.000000,0,None,0.000000,0
5,5,7,2025-11-18 08:56:49.320,0.0,0.0,5757.356,0.0,0.000,0.000,0.0,...,8,None,0.000000,0,None,0.000000,0,COMMUNICATION,86.351600,10
6,5,18,2025-11-18 17:55:01.458,0.0,0.0,0.000,0.0,0.000,0.000,0.0,...,11,SOCIAL,27.270483,11,SOCIAL,9.359950,7,COMMUNICATION,55.159333,8
7,5,27,2025-11-19 11:04:46.601,0.0,0.0,0.000,0.0,11716.922,0.000,0.0,...,10,None,0.000000,0,None,0.000000,0,COMMUNICATION,82.046850,9
8,5,45,2025-11-20 09:19:54.915,0.0,0.0,6786.366,0.0,0.000,0.000,0.0,...,14,None,0.000000,0,None,0.000000,0,COMMUNICATION,154.734333,11
9,5,58,2025-11-21 08:51:15.591,0.0,0.0,6484.552,0.0,0.000,0.000,0.0,...,12,None,0.000000,0,None,0.000000,0,SOCIAL,181.776700,6

In [9]:
from src.data_processing.passive_data_analysis import calculate_accurate_screentime_from_app_table
import pandas as pd

df = calculate_accurate_screentime_from_app_table()
df.head(10)

C:\Users\jjmur\PycharmProjects\lemurs-ml\src\database_service.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, self.connection)

Processed 75,598 accurate screentime records for 14 users

,app_user_id,app_name,calculated_start_time,last_time_used,total_time_ms,total_time_seconds
0,5,com.instagram.android,2025-11-14 18:48:07.529,2025-11-14 19:50:53.630,3766101,3766.101
1,5,com.instagram.android,2025-11-14 18:57:05.130,2025-11-14 20:07:10.224,4205094,4205.094
2,5,com.instagram.android,2025-11-14 18:57:05.182,2025-11-14 20:04:41.543,4056361,4056.361
3,5,com.google.android.apps.messaging,2025-11-14 18:59:33.221,2025-11-14 19:51:02.317,3089096,3089.096
4,5,com.google.android.apps.messaging,2025-11-14 19:12:38.257,2025-11-14 20:04:40.780,3122523,3122.523
5,5,com.sec.android.app.launcher,2025-11-14 19:19:59.334,2025-11-14 19:51:05.464,1866130,1866.130
6,5,com.instagram.android,2025-11-14 19:20:47.024,2025-11-14 20:33:14.362,4347338,4347.338
7,5,com.google.android.apps.messaging,2025-11-14 19:25:19.627,2025-11-14 20:17:46.662,3147035,3147.035
8,5,com.instagram.android,2025-11-14 19:28:08.818,2025-11-14 20:48:12.867,4804049,4804.049
9,5,com.instagram.android,2025-11-14 19:30:59.576,2025-11-14 20:56:18.013,5118437,5118.437

## Testing Model with Accurate Screentime Workaround

In [2]:
subwindow_pipeline_with_accurate_screentime = ScreentimeModelPipeline(
    target_type='sleep',
    use_subwindows=True,
    lookback_hours=12,
    subwindow_hours=3,
    save_confusion_matrices=True,
    use_accurate_method=True  # Enable accurate screentime workaround
)
results_with_accurate_screentime = subwindow_pipeline_with_accurate_screentime.fit_predict();

================================================================================
EXTRACTING AND PROCESSING DATA
================================================================================

C:\Users\jjmur\PycharmProjects\lemurs-ml\src\database_service.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, self.connection)

Processed 75,598 accurate screentime records for 14 users
================================================================================
MERGING SUB-WINDOW SCREENTIME FEATURES WITH SLEEP_LABEL
  Lookback: 12h, Sub-window: 3h
================================================================================
================================================================================
LOADING AND CLEANING SCREENTIME DATA
================================================================================

C:\Users\jjmur\PycharmProjects\lemurs-ml\src\database_service.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, self.connection)

Loaded 78,743 records from database with categories

Records before deduplication: 78,743
Records after deduplication: 32,537
Records removed: 46,206

C:\Users\jjmur\PycharmProjects\lemurs-ml\src\database_service.py:194: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, self.connection)

Processing 676 survey responses with sleep_label...

Generated 676 rows with sub-window features
Columns: ['most_used_category_sw0', 'most_used_category_time_sw0', 'num_apps_sw0', 'most_used_category_sw1', 'most_used_category_time_sw1', 'num_apps_sw1', 'most_used_category_sw2', 'most_used_category_time_sw2', 'num_apps_sw2', 'most_used_category_sw3', 'most_used_category_time_sw3', 'num_apps_sw3', 'app_user_id', 'survey_response_id', 'timestamp', 'sleep_label']

Label distribution:
sleep_label
N/A            335
at_risk        181
not_at_risk    160
Name: count, dtype: int64
Combined features: 12 hourly + 12 sub-window features

================================================================================
MODELING TIME WINDOW: 12 HOURS
================================================================================
Warning: Dropping non-numeric columns: ['most_used_category_sw0', 'most_used_category_sw1', 'most_used_category_sw2', 'most_used_category_sw3']

C:\Users\jjmur\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression:
  Accuracy: 0.5354
  F1 Score: 0.5490
  AUC: 0.4628

Random Forest:
  Accuracy: 0.6465
  F1 Score: 0.6789
  AUC: 0.2756
Saved all windows confusion matrices to: C:\Users\jjmur\PycharmProjects\lemurs-ml\data\confusion_matrices_sleep.png
Saved best models confusion matrices to: C:\Users\jjmur\PycharmProjects\lemurs-ml\data\confusion_matrices_sleep_best.png

================================================================================
SUMMARY - ALL TIME WINDOWS
================================================================================

Logistic Regression:
  Window     F1 Score     Accuracy          AUC
------------------------------------------------
    12h       0.5490       0.5354       0.4628

  Best Window: 12h (F1=0.5490)

  Confusion Matrix (Best Window):
                  Predicted
                   not_at_risk      at_risk
  Actual
      not_at_risk           25           22
          at_risk           24           28


Random Forest:
  Window     F1 Score     Accuracy          AUC
------------------------------------------------
    12h       0.6789       0.6465       0.2756

  Best Window: 12h (F1=0.6789)

  Confusion Matrix (Best Window):
                  Predicted
                   not_at_risk      at_risk
  Actual
      not_at_risk           27           20
          at_risk           15           37

In [3]:
subwindow_pipeline_with_accurate_screentime.processed_data_[12].head(10)

,app_user_id,survey_response_id,survey_timestamp,hour_0,hour_1,hour_2,hour_3,hour_4,hour_5,hour_6,...,num_apps_sw0,most_used_category_sw1,most_used_category_time_sw1,num_apps_sw1,most_used_category_sw2,most_used_category_time_sw2,num_apps_sw2,most_used_category_sw3,most_used_category_time_sw3,num_apps_sw3
0,5,1,2025-11-15 10:17:54.641,14567.574,17396.019,12000.312,0.000,0.000,0.000,0.000,...,12,None,0.000000,0,VIDEO_PLAYERS,113.940283,4,SOCIAL,266.221817,18
2,5,3,2025-11-16 10:34:25.655,0.000,3261.098,103.486,0.000,0.000,0.000,0.000,...,4,None,0.000000,0,None,0.000000,0,SOCIAL,235.342433,14
4,5,5,2025-11-17 10:59:22.663,0.000,4260.605,1616.120,2156.049,878.037,3288.775,1623.824,...,9,PERSONALIZATION,28.815983,10,None,0.000000,0,None,0.000000,0
6,5,7,2025-11-18 08:56:49.320,0.000,2163.432,447.365,16.170,6316.374,0.000,0.000,...,8,None,0.000000,0,None,0.000000,0,COMMUNICATION,86.351600,10
8,5,27,2025-11-19 11:04:46.601,3510.202,3168.296,1164.664,614.427,0.000,0.000,0.000,...,10,None,0.000000,0,None,0.000000,0,COMMUNICATION,82.046850,9
10,5,45,2025-11-20 09:19:54.915,3656.502,615.323,1281.629,3914.588,1020.159,0.000,0.000,...,14,None,0.000000,0,None,0.000000,0,COMMUNICATION,154.734333,11
11,5,58,2025-11-21 08:51:15.591,0.000,2723.727,1449.867,35.142,13101.208,0.000,0.000,...,12,None,0.000000,0,None,0.000000,0,SOCIAL,181.776700,6
13,5,84,2025-11-22 10:27:47.946,1508.849,2712.894,0.000,0.000,0.000,0.000,0.000,...,5,None,0.000000,0,None,0.000000,0,SOCIAL,198.692417,11
14,5,102,2025-11-23 09:53:29.593,0.000,1268.573,0.000,0.000,0.000,0.000,0.000,...,3,None,0.000000,0,COMMUNICATION,158.011983,4,SOCIAL,123.107700,8
16,5,124,2025-11-24 09:53:57.127,0.000,2350.268,837.020,178.717,2030.640,998.209,0.000,...,8,TOOLS,0.254667,1,None,0.000000,0,COMMUNICATION,167.142383,8